###
GET http://httpbin.org/status/301

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status != 301, "Response status is 301");
});
%}
###
GET http://httpbas22312in.org/status/301

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 301, "Response status is 301");
});
%}
